//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP10OWASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOWASP
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
