//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP10OWASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOP10OWASPEntities : DbContext
    {
        public TOP10OWASPEntities()
            : base("name=TOP10OWASPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<MESSAGE> MESSAGEs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USERACCOUNT> USERACCOUNTs { get; set; }
        public virtual DbSet<USERACCOUNTOWASP> USERACCOUNTOWASPs { get; set; }

        public System.Data.Entity.DbSet<TOP10OWASP.Models.PRODUCTOWASP> PRODUCTOWASPs { get; set; }
    }
}
